### ISSUE TITLE
Selecting Name to Meet

### ISSUE THREAD

**Issue by kushsingh28** [ayazhafiz/meetHere#1]
### Issue
When I am on the meeting feature of the web app, often times I click on the name of the person that I want to work with and the name just disappears.

### Expected behavior (of issue)
When selected during the meeting process, the name should highlight in red and move to the left - not disappear. 
### Actual behavior (of issue)
When selecting a name during the meeting process, the name should not disappear. This is an issue many people have experienced when they just newly made an account.

**Comment by kushsingh28** [comment]
Text messaging/Twilio feature on meetHere

**Comment by ayazhafiz** [comment]
Please include information on expected behavior, steps to reproduce, and proposed solutions.
