### ISSUE TITLE
Filteration of Meeting Locations

### ISSUE THREAD

**Issue by kushsingh28** [ayazhafiz/meetHere#4]
### Feature - Filtration of meeting locations
Bar of Food, Fun, Study should take you to the highest rated locations in the area and only provide locations based upon the intended purpose of the meeting. 

### Designs not implemented below: 
1. Move the title text up - creates more space and less clutter
2. the selected filter should border in red and the text color should also go red
3. The "Study" filtration bar should be aligned with the search bar. 
4. To be implemented once filtering process is figured out. 

<img width="757" alt="screen shot 2017-01-15 at 9 23 40 pm" src="https://cloud.githubusercontent.com/assets/25142365/21970081/f222b9d2-db68-11e6-978c-fd19fd97a539.png">

**Comment by ayazhafiz** [comment]
perhaps we could make this selection process after the user chooses who he wants to meet with? it would eliminate any need for clutter

**Comment by ayazhafiz** [comment]
Referencing the [Google Maps place types](https://developers.google.com/places/supported_types), I'm thinking of the following categories:

#### Food        🍝 
* restaurant
* meal_takeaway
* cafe
* bar

#### Fun          🎱 
* amusement_park
* aquarium
* art_gallery
* bowling_alley
* casino
* shopping_mall
* night_club
* movie_theater

#### Study      📚 
* cafe
* library
* university `maybe`
* school `maybe`
