### ISSUE TITLE
Design - Filter Icons ( Food, Fun, Study) 

### ISSUE THREAD

**Issue by kushsingh28** [ayazhafiz/meetHere#6]
###Design
<img width="565" alt="screen shot 2017-01-17 at 11 37 01 am" src="https://cloud.githubusercontent.com/assets/25142365/22032272/581d8f46-dca9-11e6-82e8-bcbe46c35888.png">

When selected - the icon border should be black - not pink.

**Comment by ayazhafiz** [comment]
<img width="567" alt="screenshot 2017-01-17 11 39 48" src="https://cloud.githubusercontent.com/assets/20735482/22032335/af11df32-dca9-11e6-8eae-25c351120e1a.png">
❓ ❔ ❓ 
I feel like its not as obvious. maybe a lighter border instead?

**Comment by kushsingh28** [comment]
I like that. Just the fill changing is nice. The pink border is a excessive

**Comment by ayazhafiz** [comment]
in the context of my entire page, the fill isn't that obvious bc of a distinct background. Two options are displayed below - a much lighter border or a darker pink bg

<img width="1440" alt="screenshot 2017-01-17 11 53 16" src="https://cloud.githubusercontent.com/assets/20735482/22032794/984ce45c-dcab-11e6-8a42-d0644b108912.png">
<img width="1440" alt="screenshot 2017-01-17 11 56 44" src="https://cloud.githubusercontent.com/assets/20735482/22032918/10fa644c-dcac-11e6-8052-a9149ed4a15f.png">

**Comment by kushsingh28** [comment]
hmmmm. I think the distinction is pretty apparent. The only reason the pink border and pink text was there before was because we didn't have a fill.

**Comment by ayazhafiz** [comment]
I'm just going to make the bg darker

**Comment by kushsingh28** [comment]
Okay, make it darker, then remove the pink border as well.
